name: 380CUMBERLAND
favicon: null
layout_spectrum: 0.632844
typography_spectrum: 0.9057003
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0bd9c'
    - '#060200'
    - '#8c7a56'
    - '#a12a00'
    - '#dde8ee'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
