layout_spectrum: 0.632844
typography_spectrum: 0.9057003
color:
  lightness: 0.1021036
  brandStrength: 1
  saturation: 0.4731904
  rhythmicContrast: 0.274256
  brandColors:
    - '#A4A2A2'
    - '#FFFFFF'
    - '#01CD77'
    - '#C703B4'
    - '#0177C6'
name: 380CUMBERLAND
